name: tracknet
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy==2.2.1
      - pandas==2.2.3
      - torch==2.5.1
      - tqdm==4.67.1
      - ipykernel==6.29.5
      - torchmetrics==1.6.1
      - plotly==5.24.1
      - nbformat==5.10.4
      - pytorch-lightning==2.5.0
      - hydra-core==1.3.2
      - tensorboard==2.18.0
      - matplotlib==3.10.0
      - kaleido==0.2.1
      - scipy==1.15.1
      - -e src/trackml-library
