normalizer:
  _target_: src.tracknet.data.transformations.MinMaxNormalizeXYZ
  min_xyz: [-1000.0, -1000.0, -3000.0]
  max_xyz: [1000.0, 1000.0, 3000.0]

drop_repeated:
  _target_: src.tracknet.data.transformations.DropRepeatedLayerHits