defaults:
  - dataset: trackml
  - model: step_ahead
  - user_settings: user_settings
  - _self_

data:
  train_dirs: ${user_settings.data.train_dirs}
  blacklist_dir: ${user_settings.data.blacklist_dir}

experiment:
  name: step_ahead_tracknet_trackml

training:
  seed: 42
  batch_size: 32
  max_epochs: 10
  num_workers: 4
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  resume_from: null # path to checkpoint
  limit_train_batches: 1000 # 1.0 for full dataset

logging:
  output_dir: ${hydra:run.dir}/logs